version: '2'


services:

  zookeeper:
    image: strimzi/kafka:0.11.3-kafka-2.1.0
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs
    logging:
      driver: loki
      options:
        loki-url: http://172.31.7.7:3100/api/prom/push

  kafka:
    image: strimzi/kafka:0.11.3-kafka-2.1.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    logging:
      driver: loki
      options:
        loki-url: http://172.31.7.7:3100/api/prom/push

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
        POSTGRES_PASSWORD: postgres
    logging:
      driver: loki
      options:
        loki-url: http://172.31.7.7:3100/api/prom/push

  jaeger:
    image: jaegertracing/all-in-one:1.17
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    logging:
      driver: loki
      options:
        loki-url: http://172.31.7.7:3100/api/prom/push
